INSERT IGNORE INTO tb_status_notificacao (STATUS)
VALUES
    ('NAO_ENVIADA'),
    ('ENVIADA'),
    ('ERRO_ENVIO'),
    ('NAO_RESPONDIDA'),
    ('RESPONDIDA_MENOS_24H'),
    ('RESPONDIDA_24_48H'),
    ('RESPONDIDA_MAIS_48H'),
    ('RESPONDIDA_FORA_PRAZO'),
    ('CONFIRMACAO_EXPLICITA'),
    ('CANCELAMENTO_EXPLICITO');
