INSERT IGNORE INTO tb_status_consulta (STATUS)
VALUES
    ('AGENDADA'),
    ('CANCELADA_PACIENTE'),
    ('CANCELADA_UNIDADE'),
    ('CONFIRMADA'),
    ('EM_CONTINGENCIA'),
    ('NAO_COMPARECEU'),
    ('REALIZADA'),
    ('REMARCADA');
