INSERT INTO TB_STATUS_CONSULTA (STATUS)
VALUES
    ('AGENDADA'),
    ('CANCELADA_PACIENTE'),
    ('CANCELADA_UNIDADE'),
    ('CONFIRMADA'),
    ('EM_CONTINGENCIA'),
    ('NAO_COMPARECEU'),
    ('REALIZADA'),
    ('REMARCADA')
    ON CONFLICT (NOME) DO NOTHING;
