INSERT INTO TB_STATUS_NOTIFICACAO (STATUS)
VALUES
    ('NAO_ENVIADA'),
    ('ENVIADA'),
    ('ERRO_ENVIO'),
    ('NAO_RESPONDIDA'),
    ('RESPONDIDA_MENOS_24H'),
    ('RESPONDIDA_24_48H'),
    ('RESPONDIDA_MAIS_48H'),
    ('RESPONDIDA_FORA_PRAZO'),
    ('CONFIRMACAO_EXPLICITA'),
    ('CANCELAMENTO_EXPLICITO')
    ON CONFLICT (NOME) DO NOTHING;
